server:
  address:     ":9527"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

file:
  path: "/Users/zhangyu/Documents/develop/python/learn"
#  path: "/files"

harbor:
  ip: "172.27.15.123"
  username: "admin"
  password: "Harbor12345"
  cron: "0 0 0 */3 * *"

# cron job execute time
cron:
  harbor: "0 0 0 */15 * *"

kube:
  config: "manifest/config/kube"

script:
  path: "manifest/script"

package:
  path: "manifest/pkg"

redis:
  default:
    address: "127.0.0.1:6379"

token:
  cacheMode: 2

database:
  logger:
    level:   "all"
    stdout:  true
  default:
    - link: "mysql:root:nBqYwcAq^MJCx^KJ@tcp(localhost:3306)/tokyohot?loc=Local&parseTime=true"
      debug:   true

gfcli:
  gen:
    dao:
      - link: "mysql:root:nBqYwcAq^MJCx^KJ@tcp(localhost:3306)/tokyohot?loc=Local&parseTime=true"
        tables: "user,config,image,static,upload"
