// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Config is the golang structure of table config for DAO operations like Where/Data.
type Config struct {
	g.Meta  `orm:"table:config, do:true"`
	Id      interface{} //
	Key     interface{} // 配置文件环境变量名
	Value   interface{} // 变量值
	Comment interface{} // 配置内容的解释
	SId     interface{} // Service id 关联
}
