// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Image is the golang structure of table image for DAO operations like Where/Data.
type Image struct {
	g.Meta `orm:"table:image, do:true"`
	Id     interface{} //
	Name   interface{} // 应用名称
	Tag    interface{} // 镜像tag
}
