// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. 
// =================================================================================

package do

import(
"github.com/gogf/gf/v2/frame/g"
)

// Service is the golang structure of table service for DAO operations like Where/Data.
type Service struct {
g.Meta `orm:"table:service, do:true"`
    Id interface{} //   
    Namespace interface{} //   
    Name interface{} //   
}