// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UploadDao is the data access object for table upload.
type UploadDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns UploadColumns // columns contains all the column names of Table for convenient usage.
}

// UploadColumns defines and stores column names for table upload.
type UploadColumns struct {
	Id     string //
	Name   string // 升级包名
	Md5    string // md5值
	UpTime string // 上传时间
}

// uploadColumns holds the columns for table upload.
var uploadColumns = UploadColumns{
	Id:     "id",
	Name:   "name",
	Md5:    "md5",
	UpTime: "up_time",
}

// NewUploadDao creates and returns a new DAO object for table data access.
func NewUploadDao() *UploadDao {
	return &UploadDao{
		group:   "default",
		table:   "upload",
		columns: uploadColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UploadDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UploadDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UploadDao) Columns() UploadColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UploadDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UploadDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UploadDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
