// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"pack/internal/dao/internal"
)

// internalServiceDao is internal type for wrapping internal DAO implements.
type internalServiceDao = *internal.ServiceDao

// serviceDao is the data access object for table service.
// You can define custom methods on it to extend its functionality as you wish.
type serviceDao struct {
	internalServiceDao
}

var (
	// Service is globally public accessible object for table service operations.
	Service = serviceDao{
		internal.NewServiceDao(),
	}
)

// Fill with you ideas below.
