// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"pack/internal/dao/internal"
)

// internalUploadDao is internal type for wrapping internal DAO implements.
type internalUploadDao = *internal.UploadDao

// uploadDao is the data access object for table upload.
// You can define custom methods on it to extend its functionality as you wish.
type uploadDao struct {
	internalUploadDao
}

var (
	// Upload is globally public accessible object for table upload operations.
	Upload = uploadDao{
		internal.NewUploadDao(),
	}
)

// Fill with you ideas below.
