// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Config is the golang structure for table config.
type Config struct {
	Id      uint   `json:"id"      ` //
	Name    string `json:"name"    ` //
	Value   string `json:"value"   ` //
	App     string `json:"app"     ` //
	Comment string `json:"comment" ` //
}
