// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Config is the golang structure for table config.
type Config struct {
	Id      uint   `json:"id"      ` //
	Key     string `json:"key"     ` // 配置文件环境变量名
	Value   string `json:"value"   ` // 变量值
	Comment string `json:"comment" ` // 配置内容的解释
	SId     uint   `json:"sId"     ` // Service id 关联
}
