// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Service is the golang structure for table service.
type Service struct {
	Id        uint   `json:"id"        ` //
	Namespace string `json:"namespace" ` //
	Name      string `json:"name"      ` //
}
