// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Setting is the golang structure for table setting.
type Setting struct {
	Id     uint   `json:"id"     ` //
	Config string `json:"config" ` // 配置文件变量全量json
}
