// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Static is the golang structure for table static.
type Static struct {
	Id   uint   `json:"id"   ` //
	Name string `json:"name" ` // 应用名
	Path string `json:"path" ` // 在pod中的目录
}
