// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Upload is the golang structure for table upload.
type Upload struct {
	Id     uint        `json:"id"     ` //
	Name   string      `json:"name"   ` // 升级包名
	Md5    string      `json:"md5"    ` // md5值
	UpTime *gtime.Time `json:"upTime" ` // 上传时间
}
