// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id       uint   `json:"id"       ` // 自增id
	Username string `json:"username" ` // 用户名
	Password string `json:"password" ` // 密码
	Nickname string `json:"nickname" ` // 用户别名
	Email    string `json:"email"    ` // 邮箱
	Salt     string `json:"salt"     ` // 密码加盐
}
